### ISSUE TITLE
Seed spread since May 6th

### ISSUE THREAD

**Issue by gainem** [bcmpinc/StardewHack#57]
With the update on the 6th to Tree Spread, seeds again started appearing on the farm, despite config settings. There have been no errors in the smapi log, and the only change to my mod list at the time were the updates to this mod, StardewHack and Grass Growth.

**Comment by acearohippo** [comment]
Created an account to add that this is occurring for a lot of us. Do not think the people on Nexus either a) realise bugs should be reported here on Github or 2) are comfortable creating an account for Github. Either way, can confirm that since the update on the 6th of May, tree spread is back, and at the normal rate.

**Comment by bcmpinc** [comment]
I messed up how the `OnlyPreventTapped` setting was applied. So it only prevented spreading for tapped trees when this setting was set to false. Should be fixed in v4.2.
